name: smm_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  json_annotation: ^4.6.0
  intl: ^0.17.0
  intl_utils: ^2.6.1
  flutter_svg: ^1.0.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  flutter_credit_card: ^3.0.1
  dio: ^4.0.6
  connectivity: ^3.0.6
  file_picker: ^4.6.1
  flutter_easyloading: ^3.0.5
  email_validator: ^2.0.1
  flutter_paytabs_bridge: ^2.2.8
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  generate: true
  enabled: true
  class_name: S
  main_locale: en
